image: node:latest  # Or node:20 for a specific version

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build  # This generates static files in 'build/' 
  artifacts:
    paths:
      - build/  # Use 'build/' as your output folder
  only:
    - main  # Or your default branch

pages:
  stage: deploy
  script:
    - mv build public  # Move 'build' to 'public/' (required for GitLab Pages)
  artifacts:
    paths:
      - public
  only:
    - main